In [1]:
#importing the Libraries#
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Reading the Dataset#
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
#what saved in this file#
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#create dummy data set. #drop a column#
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
#what saved in this file#
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
#catogorical data convert to numerical data#
dataset=dataset.astype(int)

In [7]:
#what saved in this file#
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [8]:
#show all columns in dataset#
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
#independent variable means input.  #split input variables. #dataset assigned to independent variable#
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [10]:
#what saved in this file#
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [11]:
#dependent variable means output.  #split output variables. #dataset assigned to dependent variable#
dependent=dataset[['charges']]

In [12]:
#what saved in this file#
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [13]:
#machine learning algorithms provider is sklearn #split train set and test set#
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(independent, dependent,test_size=0.2,random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
#Model creation#
from sklearn.model_selection import GridSearchCV

from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegressionCV

X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

log_reg_cv = LogisticRegressionCV(max_iter=10000, cv=5)
param_grid = {
    'penalty': ['l2', 'none'],                # L2 regularization or no regularization
    'solver': ['lbfgs', 'liblinear', 'saga'], # Solvers that handle different penalties
    'fit_intercept': [True, False],           # Whether to calculate the intercept
    'class_weight': [None, 'balanced'],}       # Adjust class imbalance if necessary

grid_search = GridSearchCV(estimator=log_reg_cv, param_grid=param_grid, 
                          scoring='accuracy', cv=5, verbose=1, n_jobs=-1)

#fitting the model for grid search
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
60 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1760, in fit
    self._validate_params()
  File "C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegressionCV must be a str among {'elasticnet', 'l2', 'l1'}. Got 'none' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [0.96703297 0.95824176 0.91428571        nan        nan        nan
 0.96043956 0.95604396 0.91428571        nan        nan        nan
 0.96483516 0.95164835 0.90989011        nan        nan        nan
 0.96923077 0.95384615 0.90989011        nan        nan        nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegressionCV(cv=5, max_iter=10000),
             n_jobs=-1,
             param_grid={'class_weight': [None, 'balanced'],
                         'fit_intercept': [True, False],
                         'penalty': ['l2', 'none'],
                         'solver': ['lbfgs', 'liblinear', 'saga']},
             scoring='accuracy', verbose=1)

In [16]:
# Print best parameter afterr tuning#
#Print(grid.best_params_)

re=grid_search.cv_results_

print("The R_score value for best parameter {}:".format(grid_search.best_params_))
print("Best r2 Score:", grid_search.best_score_)

The R_score value for best parameter {'class_weight': 'balanced', 'fit_intercept': False, 'penalty': 'l2', 'solver': 'lbfgs'}:
Best r2 Score: 0.9692307692307693

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_fit_intercept,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,14.811144,2.563925,0.001001,0.000895,None,True,l2,lbfgs,"{'class_weight': None, 'fit_intercept': True, ...",0.956044,0.967033,0.989011,0.978022,0.945055,0.967033,0.015541,2
1,0.441167,0.011926,0.003526,0.006099,None,True,l2,liblinear,"{'class_weight': None, 'fit_intercept': True, ...",0.956044,0.945055,0.978022,0.978022,0.934066,0.958242,0.017582,5
2,7.625792,0.319635,0.000603,0.000803,None,True,l2,saga,"{'class_weight': None, 'fit_intercept': True, ...",0.956044,0.879121,0.956044,0.868132,0.912088,0.914286,0.037038,9
3,0.001001,0.000632,0.000000,0.000000,None,True,none,lbfgs,"{'class_weight': None, 'fit_intercept': True, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
4,0.000999,0.000002,0.000000,0.000000,None,True,none,liblinear,"{'class_weight': None, 'fit_intercept': True, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
5,0.000999,0.000002,0.000000,0.000000,None,True,none,saga,"{'class_weight': None, 'fit_intercept': True, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
6,15.700530,4.632797,0.003525,0.006100,None,False,l2,lbfgs,"{'class_weight': None, 'fit_intercept': False,...",0.956044,0.945055,0.989011,0.978022,0.934066,0.960440,0.020382,4
7,0.404814,0.023388,0.003125,0.006251,None,False,l2,liblinear,"{'class_weight': None, 'fit_intercept': False,...",0.956044,0.934066,0.978022,0.978022,0.934066,0.956044,0.019658,6
8,7.412395,0.329001,0.001405,0.000490,None,False,l2,saga,"{'class_weight': None, 'fit_intercept': False,...",0.956044,0.879121,0.956044,0.868132,0.912088,0.914286,0.037038,9
9,0.000600,0.000490,0.000000,0.000000,None,False,none,lbfgs,"{'class_weight': None, 'fit_intercept': False,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
10,0.000601,0.000490,0.000000,0.000000,None,False,none,liblinear,"{'class_weight': None, 'fit_intercept': False,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
11,0.000800,0.000400,0.000000,0.000000,None,False,none,saga,"{'class_weight': None, 'fit_intercept': False,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
12,15.706203,1.982678,0.000401,0.000801,balanced,True,l2,lbfgs,"{'class_weight': 'balanced', 'fit_intercept': ...",0.945055,0.967033,0.989011,0.989011,0.934066,0.964835,0.022413,3
13,0.417273,0.008532,0.000000,0.000000,balanced,True,l2,liblinear,"{'class_weight': 'balanced', 'fit_intercept': ...",0.956044,0.934066,0.967033,0.978022,0.923077,0.951648,0.020382,8
14,13.260329,1.444831,0.012012,0.018902,balanced,True,l2,saga,"{'class_weight': 'balanced', 'fit_intercept': ...",0.956044,0.857143,0.967033,0.879121,0.890110,0.909890,0.043625,11
15,0.001198,0.000400,0.000000,0.000000,balanced,True,none,lbfgs,"{'class_weight': 'balanced', 'fit_intercept': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
16,0.000801,0.000400,0.000000,0.000000,balanced,True,none,liblinear,"{'class_weight': 'balanced', 'fit_intercept': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
17,0.001200,0.000399,0.000000,0.000000,balanced,True,none,saga,"{'class_weight': 'balanced', 'fit_intercept': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
18,27.238263,5.738888,0.001453,0.000557,balanced,False,l2,lbfgs,"{'class_weight': 'balanced', 'fit_intercept': ...",0.956044,0.967033,1.000000,0.978022,0.945055,0.969231,0.018906,1
19,0.518229,0.022068,0.002602,0.002246,balanced,False,l2,liblinear,"{'class_weight': 'balanced', 'fit_intercept': ...",0.956044,0.956044,0.956044,0.978022,0.923077,0.953846,0.017582,7
20,11.064285,1.012579,0.001408,0.000489,balanced,False,l2,saga,"{'class_weight': 'balanced', 'fit_intercept': ...",0.956044,0.857143,0.967033,0.879121,0.890110,0.909890,0.043625,11
21,0.000999,0.000003,0.000000,0.000000,balanced,False,none,lbfgs,"{'class_weight': 'balanced', 'fit_intercept': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
22,0.001016,0.000033,0.000000,0.000000,balanced,False,none,liblinear,"{'class_weight': 'balanced', 'fit_intercept': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
23,0.001000,0.000002,0.000000,0.000000,balanced,False,none,saga,"{'class_weight': 'balanced', 'fit_intercept': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13

In [19]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("children:"))
sex_male_input=int(input("sex Male 0 or 1:"))
smoker_yes_input=int(input("smoker yes 0 or 1:"))

Age: 34
BMI: 45
children: 2
sex Male 0 or 1: 1
smoker yes 0 or 1: 0

In [20]:
Future_Prediction=grid_search.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

ValueError: X has 5 features, but LogisticRegressionCV is expecting 30 features as input.